all : prod cons dph
.PHONY : clean


prod : prod.c
	gcc prod.c -lrt -lpthread -lm -o prod

cons : cons.c
	gcc cons.c -lrt -lpthread -lm -o cons

dph : dph.c
	gcc dph.c -lrt -lpthread -lm -o dph

clean : 
	rm  prod
	rm  cons
	rm  dph 
	rm  *.o
